#!/bin/bash
## RabbitMQ for CentOS 7
sudo yum update -y
sudo yum install epel-release -y
sudo install socat -y
sudo install erlang -y
sudo yum install wget -y
cd /tmp/
wget https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.10/rabbitmq-server-3.6.10-1.e17.noarch.rpm
sudo rpm --import https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
sudo rpm -Uuh /tmp/rabbitmq-server-3.6.10-1.e17.noarch.rpm
sudo systemctl start rabbitmq-server
sudo systemctl enable rabbitmq-server
sudo systemctl status rabbitmq-server
sudo sh -c 'echo "[{rabbit, [{loopback_users, []}]}]." > /etc/rabbitmq/rabbitmq.config'
sudo rabbitmqctl add_user test test
sudo rabbitmqctl set_user_tags test administrator
sudo systemctl restart rabbitmq-server
